apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aws-opensearch-spring-cluster
  region: ca-central-1

vpc:
  subnets:
    private:
      us-east-1c: { id: subnet-03111d20473ad03b3 }
      us-east-1d: { id: subnet-09d05a8a02bf37f16 }
      us-east-1b: { id: subnet-0e700de1a7991d27f }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t3.small
    desiredCapacity: 2
    privateNetworking: true
  - name: ng-2-builders
    labels: { role: builders }
    instanceType: t3.small
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true