apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-opensearch-spring-deployment
  labels:
    app: aws-opensearch-spring-deployment
spec:
  selector:
    matchLabels:
      app: aws-opensearch-spring-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: aws-opensearch-spring-deployment
    spec:
      containers:
        - name: aws-opensearch-spring-container
          image: freeever/aws-opensearch-spring
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: aws-opensearch-spring-service
  labels:
    app: aws-opensearch-spring-service
spec:
  ports:
    - nodePort: 31148
      port: 8080
      targetPort: 5000
      protocol: TCP
  selector:
    app: aws-opensearch-spring-deployment
  type: NodePort
