apiVersion: v1
kind: Service
metadata:
  name: aws-opensearch-spring-service
spec:
  selector:
    app: aws-opensearch-spring
  ports:
    - nodePort: 31479    #external traffic
      port: 8080         #port of this service. Cluster members talk via this port
      protocol: TCP
      targetPort: 5000   #where container is actually running
  type: LoadBalancer